// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/Area2.CloudShader" {
Properties {
 Vector1_9E77EB2D ("Scroll Speed ", Float) = 0.000000
 Color_7A13FCE5 ("Color", Color) = (0.144679,0.098389,0.311321,0.000000)
 Color_7896B6F ("Color (1)", Color) = (0.464478,0.424350,0.603774,0.000000)
 Vector1_A0FD746E ("Cloud Cover ", Float) = 0.000000
 Vector1_9CBBF7B8 ("Additional Fallout ", Float) = 0.000000
 Vector1_19F93CF9 ("Density ", Float) = 0.000000
}
SubShader { 
 Tags { "QUEUE"="Transparent+0" "RenderType"="Transparent" "RenderPipeline"="LightweightPipeline" }


 // Stats for Vertex shader:
 //        d3d11: 341 math
 // Stats for Fragment shader:
 //        d3d11: 13 math, 1 texture
 Pass {
  Tags { "QUEUE"="Transparent+0" "RenderType"="Transparent" "RenderPipeline"="LightweightPipeline" }
  ZWrite Off
  Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 341 math, 7 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (4880 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 2256
  Vector4 _TimeParameters at 1504
  Vector3 _WorldSpaceCameraPos at 1520
  Vector4 _ProjectionParams at 1536
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 2 {
  Float Vector1_9E77EB2D at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 3   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xyz         4     NONE   float   xyz 
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[145], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyzw
      dcl_output o7.xyzw
      dcl_temps 7
   0: mul r0.x, cb0[94].z, cb2[0].x
   1: mul r0.yzw, v0.yyyy, cb1[1].xxyz
   2: mad r0.yzw, cb1[0].xxyz, v0.xxxx, r0.yyzw
   3: mad r0.yzw, cb1[2].xxyz, v0.zzzz, r0.yyzw
   4: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.yzwy
   5: add r0.yzw, r0.yyzw, cb1[3].xxyz
   6: add o5.xyz, -r0.yzwy, cb0[95].xyzx
   7: mad r0.xy, r0.xxxx, l(0.500000, 0.500000, 0.000000, 0.000000), r1.xzxx
   8: mul r0.xy, r0.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
   9: round_ni r0.zw, r0.xxxy
  10: frc r0.xy, r0.xyxx
  11: add r2.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
  12: mul r3.xyzw, r2.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
  13: ge r3.xyzw, r3.xyzw, -r3.zwzw
  14: movc r3.xyzw, r3.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  15: mul r2.xy, r2.xyxx, r3.zwzz
  16: frc r2.xy, r2.xyxx
  17: mul r2.xy, r2.xyxx, r3.xyxx
  18: mad r1.w, r2.x, l(34.000000), l(1.000000)
  19: mul r1.w, r2.x, r1.w
  20: mul r2.x, r1.w, l(289.000000)
  21: ge r2.x, r2.x, -r2.x
  22: movc r2.xz, r2.xxxx, l(289.000000,0,0.003460,0), l(-289.000000,0,-0.003460,0)
  23: mul r1.w, r1.w, r2.z
  24: frc r1.w, r1.w
  25: mad r1.w, r2.x, r1.w, r2.y
  26: mad r2.x, r1.w, l(34.000000), l(1.000000)
  27: mul r1.w, r1.w, r2.x
  28: mul r2.x, r1.w, l(289.000000)
  29: ge r2.x, r2.x, -r2.x
  30: movc r2.xy, r2.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  31: mul r1.w, r1.w, r2.y
  32: frc r1.w, r1.w
  33: mul r1.w, r1.w, r2.x
  34: mul r1.w, r1.w, l(0.024390)
  35: frc r1.w, r1.w
  36: mad r2.xy, r1.wwww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
  37: round_ni r1.w, r2.y
  38: add r3.x, -r1.w, r2.x
  39: add r3.y, |r2.x|, l(-0.500000)
  40: dp2 r1.w, r3.xyxx, r3.xyxx
  41: rsq r1.w, r1.w
  42: mul r2.xy, r1.wwww, r3.xyxx
  43: add r2.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
  44: dp2 r1.w, r2.xyxx, r2.zwzz
  45: add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
  46: mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  47: ge r3.xyzw, r3.xyzw, -r3.xyzw
  48: movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  49: movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  50: mul r2.zw, r2.zzzw, r4.zzzw
  51: mul r2.xy, r2.xyxx, r3.zwzz
  52: frc r2.xyzw, r2.xyzw
  53: mul r2.xy, r2.xyxx, r3.xyxx
  54: mul r2.zw, r2.zzzw, r4.xxxy
  55: mad r3.x, r2.z, l(34.000000), l(1.000000)
  56: mul r2.z, r2.z, r3.x
  57: mul r3.x, r2.z, l(289.000000)
  58: ge r3.x, r3.x, -r3.x
  59: movc r3.xy, r3.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  60: mul r2.z, r2.z, r3.y
  61: frc r2.z, r2.z
  62: mad r2.z, r3.x, r2.z, r2.w
  63: mad r2.w, r2.z, l(34.000000), l(1.000000)
  64: mul r2.z, r2.z, r2.w
  65: mul r2.w, r2.z, l(289.000000)
  66: ge r2.w, r2.w, -r2.w
  67: movc r3.xy, r2.wwww, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  68: mul r2.z, r2.z, r3.y
  69: frc r2.z, r2.z
  70: mul r2.z, r2.z, r3.x
  71: mul r2.z, r2.z, l(0.024390)
  72: frc r2.z, r2.z
  73: mad r2.zw, r2.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
  74: round_ni r2.w, r2.w
  75: add r3.x, -r2.w, r2.z
  76: add r3.y, |r2.z|, l(-0.500000)
  77: dp2 r2.z, r3.xyxx, r3.xyxx
  78: rsq r2.z, r2.z
  79: mul r2.zw, r2.zzzz, r3.xxxy
  80: add r3.xyzw, r0.xyxy, l(0.000000, -1.000000, -1.000000, 0.000000)
  81: dp2 r2.z, r2.zwzz, r3.zwzz
  82: add r1.w, r1.w, -r2.z
  83: mul r3.zw, r0.xxxy, r0.xxxy
  84: mul r3.zw, r0.xxxy, r3.zzzw
  85: mad r4.xy, r0.xyxx, l(6.000000, 6.000000, 0.000000, 0.000000), l(-15.000000, -15.000000, 0.000000, 0.000000)
  86: mad r4.xy, r0.xyxx, r4.xyxx, l(10.000000, 10.000000, 0.000000, 0.000000)
  87: mul r3.zw, r3.zzzw, r4.xxxy
  88: mad r1.w, r3.w, r1.w, r2.z
  89: mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  90: ge r4.xyzw, r4.xyzw, -r4.zwzw
  91: movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  92: mul r0.zw, r0.zzzw, r4.zzzw
  93: frc r0.zw, r0.zzzw
  94: mul r0.zw, r0.zzzw, r4.xxxy
  95: mad r2.z, r0.z, l(34.000000), l(1.000000)
  96: mul r0.z, r0.z, r2.z
  97: mul r2.z, r0.z, l(289.000000)
  98: ge r2.z, r2.z, -r2.z
  99: movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 100: mul r0.z, r0.z, r2.w
 101: frc r0.z, r0.z
 102: mad r0.z, r2.z, r0.z, r0.w
 103: mad r0.w, r0.z, l(34.000000), l(1.000000)
 104: mul r0.z, r0.z, r0.w
 105: mul r0.w, r0.z, l(289.000000)
 106: ge r0.w, r0.w, -r0.w
 107: movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 108: mul r0.z, r0.z, r2.w
 109: frc r0.z, r0.z
 110: mul r0.z, r0.z, r2.z
 111: mul r0.z, r0.z, l(0.024390)
 112: frc r0.z, r0.z
 113: mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
 114: round_ni r0.w, r0.w
 115: add r4.x, -r0.w, r0.z
 116: add r4.y, |r0.z|, l(-0.500000)
 117: dp2 r0.z, r4.xyxx, r4.xyxx
 118: rsq r0.z, r0.z
 119: mul r0.zw, r0.zzzz, r4.xxxy
 120: dp2 r0.x, r0.zwzz, r0.xyxx
 121: mad r0.y, r2.x, l(34.000000), l(1.000000)
 122: mul r0.y, r2.x, r0.y
 123: mul r0.z, r0.y, l(289.000000)
 124: ge r0.z, r0.z, -r0.z
 125: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 126: mul r0.y, r0.w, r0.y
 127: frc r0.y, r0.y
 128: mad r0.y, r0.z, r0.y, r2.y
 129: mad r0.z, r0.y, l(34.000000), l(1.000000)
 130: mul r0.y, r0.y, r0.z
 131: mul r0.z, r0.y, l(289.000000)
 132: ge r0.z, r0.z, -r0.z
 133: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 134: mul r0.y, r0.w, r0.y
 135: frc r0.y, r0.y
 136: mul r0.y, r0.y, r0.z
 137: mul r0.y, r0.y, l(0.024390)
 138: frc r0.y, r0.y
 139: mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
 140: round_ni r0.z, r0.z
 141: add r2.x, -r0.z, r0.y
 142: add r2.y, |r0.y|, l(-0.500000)
 143: dp2 r0.y, r2.xyxx, r2.xyxx
 144: rsq r0.y, r0.y
 145: mul r0.yz, r0.yyyy, r2.xxyx
 146: dp2 r0.y, r0.yzyy, r3.xyxx
 147: add r0.y, -r0.x, r0.y
 148: mad r0.x, r3.w, r0.y, r0.x
 149: add r0.y, -r0.x, r1.w
 150: mad r0.x, r3.z, r0.y, r0.x
 151: add r0.x, r0.x, l(0.500000)
 152: mad r2.xyzw, cb0[94].zzzz, cb2[0].xxxx, r1.xzxz
 153: round_ni r0.yz, r2.zzwz
 154: add r3.xy, r0.yzyy, l(1.000000, 1.000000, 0.000000, 0.000000)
 155: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 156: sincos r0.w, null, r0.w
 157: mul r0.w, r0.w, l(43758.546875)
 158: frc r0.w, r0.w
 159: frc r3.xy, r2.zwzz
 160: mul r2.xyzw, r2.xyzw, l(0.500000, 0.500000, 0.250000, 0.250000)
 161: mul r3.zw, r3.xxxy, r3.xxxy
 162: mad r3.xy, -r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
 163: mul r4.xy, r3.xyxx, r3.zwzz
 164: mad r3.xy, -r3.zwzz, r3.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 165: mul r0.w, r0.w, r4.x
 166: add r5.xyzw, r0.yzyz, l(1.000000, 0.000000, 0.000000, 1.000000)
 167: dp2 r0.y, r0.yzyy, l(12.989800, 78.233002, 0.000000, 0.000000)
 168: sincos r0.y, null, r0.y
 169: mul r0.y, r0.y, l(43758.546875)
 170: frc r0.y, r0.y
 171: dp2 r0.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 172: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 173: sincos r1.w, null, r1.w
 174: mul r1.w, r1.w, l(43758.546875)
 175: frc r1.w, r1.w
 176: mul r1.w, r1.w, r4.x
 177: mad r0.y, r3.x, r0.y, r1.w
 178: sincos r0.z, null, r0.z
 179: mul r0.z, r0.z, l(43758.546875)
 180: frc r0.z, r0.z
 181: mad r0.z, r3.x, r0.z, r0.w
 182: mul r0.z, r0.z, r4.y
 183: mad r0.y, r3.y, r0.y, r0.z
 184: round_ni r3.xyzw, r2.xyzw
 185: frc r2.xyzw, r2.xyzw
 186: add r4.xyzw, r3.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 187: dp2 r0.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 188: dp2 r0.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 189: sincos r0.zw, null, r0.zzzw
 190: mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 191: frc r0.zw, r0.zzzw
 192: add r4.xyzw, r3.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 193: dp2 r1.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 194: dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 195: sincos r4.x, null, r4.x
 196: mul r4.x, r4.x, l(43758.546875)
 197: frc r4.x, r4.x
 198: sincos r1.w, null, r1.w
 199: mul r1.w, r1.w, l(43758.546875)
 200: frc r1.w, r1.w
 201: mul r5.xyzw, r2.xyzw, r2.xyzw
 202: mad r2.xyzw, -r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 203: mul r6.xyzw, r2.xyzw, r5.xyzw
 204: mad r2.xyzw, -r5.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 205: mul r1.w, r1.w, r6.x
 206: mad r0.z, r2.x, r0.z, r1.w
 207: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 208: sincos r1.w, null, r1.w
 209: mul r1.w, r1.w, l(43758.546875)
 210: frc r1.w, r1.w
 211: mul r0.zw, r0.zzzw, r6.yyyx
 212: mad r0.w, r2.x, r1.w, r0.w
 213: mad r0.z, r2.y, r0.w, r0.z
 214: mul r0.z, r0.z, l(0.250000)
 215: mad r0.y, r0.y, l(0.125000), r0.z
 216: add r5.xyzw, r3.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 217: dp2 r0.z, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 218: sincos r0.z, null, r0.z
 219: mul r0.z, r0.z, l(43758.546875)
 220: dp2 r0.w, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 221: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 222: sincos r1.w, null, r1.w
 223: mul r1.w, r1.w, l(43758.546875)
 224: frc r1.w, r1.w
 225: sincos r0.w, null, r0.w
 226: mul r0.w, r0.w, l(43758.546875)
 227: frc r0.zw, r0.zzzw
 228: mul r0.w, r0.w, r6.z
 229: mad r0.w, r2.z, r1.w, r0.w
 230: mul r0.w, r0.w, r6.w
 231: mul r1.w, r4.x, r6.z
 232: mad r0.z, r2.z, r0.z, r1.w
 233: mad r0.z, r2.w, r0.z, r0.w
 234: mad r0.y, r0.z, l(0.500000), r0.y
 235: add r0.x, r0.y, r0.x
 236: mad r0.yz, cb0[94].xxxx, cb0[94].xxxx, r1.xxzx
 237: mov o1.xyz, r1.xyzx
 238: mul r1.xyzw, r0.yzyz, l(0.500000, 0.500000, 0.250000, 0.250000)
 239: round_ni r2.xyzw, r1.xyzw
 240: frc r1.xyzw, r1.xyzw
 241: add r3.xyzw, r2.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 242: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 243: dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 244: sincos r3.x, null, r3.x
 245: mul r3.x, r3.x, l(43758.546875)
 246: frc r3.x, r3.x
 247: sincos r0.w, null, r0.w
 248: mul r0.yzw, r0.yyzw, l(0.000000, 0.125000, 0.125000, 43758.546875)
 249: frc r0.w, r0.w
 250: mul r4.xyzw, r1.xyzw, r1.xyzw
 251: mad r1.xyzw, -r1.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 252: mul r5.xyzw, r1.xyzw, r4.xyzw
 253: mad r1.xyzw, -r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 254: mul r3.x, r3.x, r5.z
 255: mad r0.w, r1.z, r0.w, r3.x
 256: mul r0.w, r0.w, r5.w
 257: dp2 r3.x, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 258: sincos r3.x, null, r3.x
 259: mul r3.x, r3.x, l(43758.546875)
 260: frc r3.x, r3.x
 261: add r4.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 262: dp2 r2.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 263: dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 264: sincos r2.zw, null, r2.zzzw
 265: mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 266: frc r2.zw, r2.zzzw
 267: mul r2.zw, r2.zzzw, r5.zzzx
 268: mad r1.z, r1.z, r3.x, r2.z
 269: mad r0.w, r1.w, r1.z, r0.w
 270: mul r0.w, r0.w, l(0.250000)
 271: dp2 r1.z, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 272: add r3.xyzw, r2.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 273: sincos r1.z, null, r1.z
 274: mul r1.z, r1.z, l(43758.546875)
 275: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 276: dp2 r2.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 277: sincos r2.x, null, r2.x
 278: mul r2.x, r2.x, l(43758.546875)
 279: frc r2.x, r2.x
 280: mad r2.x, r1.x, r2.x, r2.w
 281: mul r2.x, r2.x, r5.y
 282: sincos r1.w, null, r1.w
 283: mul r1.w, r1.w, l(43758.546875)
 284: frc r1.zw, r1.zzzw
 285: mul r1.w, r1.w, r5.x
 286: mad r1.x, r1.x, r1.z, r1.w
 287: mad r1.x, r1.y, r1.x, r2.x
 288: mad r0.w, r1.x, l(0.125000), r0.w
 289: round_ni r1.xy, r0.yzyy
 290: frc r0.yz, r0.yyzy
 291: add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
 292: dp2 r1.z, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 293: sincos r1.z, null, r1.z
 294: mul r1.z, r1.z, l(43758.546875)
 295: frc r1.z, r1.z
 296: mul r2.xy, r0.yzyy, r0.yzyy
 297: mad r0.yz, -r0.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
 298: mul r2.zw, r0.yyyz, r2.xxxy
 299: mad r0.yz, -r2.xxyx, r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
 300: add r3.xyzw, r1.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 301: dp2 r1.x, r1.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 302: sincos r1.x, null, r1.x
 303: mul r1.x, r1.x, l(43758.546875)
 304: dp2 r1.y, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 305: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 306: sincos r1.yw, null, r1.yyyw
 307: mul r1.yw, r1.yyyw, l(0.000000, 43758.546875, 0.000000, 43758.546875)
 308: frc r1.xyw, r1.xyxw
 309: mul r1.zw, r1.zzzw, r2.zzzz
 310: mad r1.x, r0.y, r1.x, r1.w
 311: mad r0.y, r0.y, r1.y, r1.z
 312: mul r0.y, r0.y, r2.w
 313: mad r0.y, r0.z, r1.x, r0.y
 314: mad r0.y, r0.y, l(0.500000), r0.w
 315: mad r0.x, r0.x, r0.y, l(-0.500000)
 316: dp3 r0.y, cb1[1].xyzx, cb1[1].xyzx
 317: sqrt r0.y, r0.y
 318: mul r0.x, r0.y, r0.x
 319: mad r0.xyz, cb1[5].xyzx, r0.xxxx, cb1[7].xyzx
 320: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
 321: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
 322: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
 323: add r0.xyzw, r0.xyzw, cb1[3].xyzw
 324: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 325: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 326: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 327: mad o0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 328: dp3 r0.x, v1.xyzx, cb1[4].xyzx
 329: dp3 r0.y, v1.xyzx, cb1[5].xyzx
 330: dp3 r0.z, v1.xyzx, cb1[6].xyzx
 331: dp3 r0.w, r0.xyzx, r0.xyzx
 332: rsq r0.w, r0.w
 333: mul r0.xyz, r0.wwww, r0.xyzx
 334: mov o2.xyz, r0.xyzx
 335: mul r1.xyz, v2.yyyy, cb1[1].xyzx
 336: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
 337: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
 338: dp3 r0.w, r1.xyzx, r1.xyzx
 339: rsq r0.w, r0.w
 340: mul r1.xyz, r0.wwww, r1.xyzx
 341: mov o3.xyz, r1.xyzx
 342: mul r2.xyz, r0.zxyz, r1.yzxy
 343: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
 344: mul o4.xyz, r0.xyzx, v2.wwww
 345: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
 346: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
 347: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
 348: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
 349: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 350: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 351: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 352: mad r0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 353: mul r0.y, r0.y, cb0[96].x
 354: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
 355: mov o6.zw, r0.zzzw
 356: add o6.xy, r1.zzzz, r1.xwxx
 357: mov o7.xyzw, v3.xyzw
 358: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 13 math, 2 temp registers, 1 textures
Set 2D Texture "_CameraDepthTexture" to slot 0

Constant Buffer "$Globals" (4880 bytes) on slot 0 {
  Vector4 _ZBufferParams at 1568
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 1 {
  Vector4 Color_7896B6F at 32
  Float Vector1_A0FD746E at 48
  Float Vector1_9CBBF7B8 at 52
  Float Vector1_19F93CF9 at 56
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 3   xyz         1     NONE   float       
// TEXCOORD                 4   xyz         2     NONE   float       
// TEXCOORD                 5   xyz         3     NONE   float       
// TEXCOORD                 6   xyz         4     NONE   float       
// TEXCOORD                 7   xyz         5     NONE   float       
// TEXCOORD                 8   xyzw        6     NONE   float   xy w
// TEXCOORD                 9   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[99], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v6.xyw
      dcl_output o0.xyzw
      dcl_temps 2
   0: mad r0.x, cb1[3].x, l(2.000000), cb1[3].y
   1: add r0.x, r0.x, -cb1[3].x
   2: div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
   3: mul_sat r0.x, r0.x, -cb1[3].x
   4: mad r0.y, r0.x, l(-2.000000), l(3.000000)
   5: mul r0.x, r0.x, r0.x
   6: mul r0.x, r0.x, r0.y
   7: div r0.yz, v6.xxyx, v6.wwww
   8: sample r1.xyzw, r0.yzyy, t0.xyzw, s0
   9: mad r0.y, cb0[98].z, r1.x, cb0[98].w
  10: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
  11: add r0.y, r0.y, -v6.w
  12: mul_sat r0.y, r0.y, cb1[3].z
  13: mul o0.w, r0.y, r0.x
  14: mov o0.xyz, cb1[2].xyzx
  15: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Global Keywords: DIRLIGHTMAP_COMBINED 
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 341 math, 7 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (4880 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 2256
  Vector4 _TimeParameters at 1504
  Vector3 _WorldSpaceCameraPos at 1520
  Vector4 _ProjectionParams at 1536
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 2 {
  Float Vector1_9E77EB2D at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 3   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xyz         4     NONE   float   xyz 
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[145], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyzw
      dcl_output o7.xyzw
      dcl_temps 7
   0: mul r0.x, cb0[94].z, cb2[0].x
   1: mul r0.yzw, v0.yyyy, cb1[1].xxyz
   2: mad r0.yzw, cb1[0].xxyz, v0.xxxx, r0.yyzw
   3: mad r0.yzw, cb1[2].xxyz, v0.zzzz, r0.yyzw
   4: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.yzwy
   5: add r0.yzw, r0.yyzw, cb1[3].xxyz
   6: add o5.xyz, -r0.yzwy, cb0[95].xyzx
   7: mad r0.xy, r0.xxxx, l(0.500000, 0.500000, 0.000000, 0.000000), r1.xzxx
   8: mul r0.xy, r0.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
   9: round_ni r0.zw, r0.xxxy
  10: frc r0.xy, r0.xyxx
  11: add r2.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
  12: mul r3.xyzw, r2.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
  13: ge r3.xyzw, r3.xyzw, -r3.zwzw
  14: movc r3.xyzw, r3.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  15: mul r2.xy, r2.xyxx, r3.zwzz
  16: frc r2.xy, r2.xyxx
  17: mul r2.xy, r2.xyxx, r3.xyxx
  18: mad r1.w, r2.x, l(34.000000), l(1.000000)
  19: mul r1.w, r2.x, r1.w
  20: mul r2.x, r1.w, l(289.000000)
  21: ge r2.x, r2.x, -r2.x
  22: movc r2.xz, r2.xxxx, l(289.000000,0,0.003460,0), l(-289.000000,0,-0.003460,0)
  23: mul r1.w, r1.w, r2.z
  24: frc r1.w, r1.w
  25: mad r1.w, r2.x, r1.w, r2.y
  26: mad r2.x, r1.w, l(34.000000), l(1.000000)
  27: mul r1.w, r1.w, r2.x
  28: mul r2.x, r1.w, l(289.000000)
  29: ge r2.x, r2.x, -r2.x
  30: movc r2.xy, r2.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  31: mul r1.w, r1.w, r2.y
  32: frc r1.w, r1.w
  33: mul r1.w, r1.w, r2.x
  34: mul r1.w, r1.w, l(0.024390)
  35: frc r1.w, r1.w
  36: mad r2.xy, r1.wwww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
  37: round_ni r1.w, r2.y
  38: add r3.x, -r1.w, r2.x
  39: add r3.y, |r2.x|, l(-0.500000)
  40: dp2 r1.w, r3.xyxx, r3.xyxx
  41: rsq r1.w, r1.w
  42: mul r2.xy, r1.wwww, r3.xyxx
  43: add r2.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
  44: dp2 r1.w, r2.xyxx, r2.zwzz
  45: add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
  46: mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  47: ge r3.xyzw, r3.xyzw, -r3.xyzw
  48: movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  49: movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  50: mul r2.zw, r2.zzzw, r4.zzzw
  51: mul r2.xy, r2.xyxx, r3.zwzz
  52: frc r2.xyzw, r2.xyzw
  53: mul r2.xy, r2.xyxx, r3.xyxx
  54: mul r2.zw, r2.zzzw, r4.xxxy
  55: mad r3.x, r2.z, l(34.000000), l(1.000000)
  56: mul r2.z, r2.z, r3.x
  57: mul r3.x, r2.z, l(289.000000)
  58: ge r3.x, r3.x, -r3.x
  59: movc r3.xy, r3.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  60: mul r2.z, r2.z, r3.y
  61: frc r2.z, r2.z
  62: mad r2.z, r3.x, r2.z, r2.w
  63: mad r2.w, r2.z, l(34.000000), l(1.000000)
  64: mul r2.z, r2.z, r2.w
  65: mul r2.w, r2.z, l(289.000000)
  66: ge r2.w, r2.w, -r2.w
  67: movc r3.xy, r2.wwww, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  68: mul r2.z, r2.z, r3.y
  69: frc r2.z, r2.z
  70: mul r2.z, r2.z, r3.x
  71: mul r2.z, r2.z, l(0.024390)
  72: frc r2.z, r2.z
  73: mad r2.zw, r2.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
  74: round_ni r2.w, r2.w
  75: add r3.x, -r2.w, r2.z
  76: add r3.y, |r2.z|, l(-0.500000)
  77: dp2 r2.z, r3.xyxx, r3.xyxx
  78: rsq r2.z, r2.z
  79: mul r2.zw, r2.zzzz, r3.xxxy
  80: add r3.xyzw, r0.xyxy, l(0.000000, -1.000000, -1.000000, 0.000000)
  81: dp2 r2.z, r2.zwzz, r3.zwzz
  82: add r1.w, r1.w, -r2.z
  83: mul r3.zw, r0.xxxy, r0.xxxy
  84: mul r3.zw, r0.xxxy, r3.zzzw
  85: mad r4.xy, r0.xyxx, l(6.000000, 6.000000, 0.000000, 0.000000), l(-15.000000, -15.000000, 0.000000, 0.000000)
  86: mad r4.xy, r0.xyxx, r4.xyxx, l(10.000000, 10.000000, 0.000000, 0.000000)
  87: mul r3.zw, r3.zzzw, r4.xxxy
  88: mad r1.w, r3.w, r1.w, r2.z
  89: mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  90: ge r4.xyzw, r4.xyzw, -r4.zwzw
  91: movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  92: mul r0.zw, r0.zzzw, r4.zzzw
  93: frc r0.zw, r0.zzzw
  94: mul r0.zw, r0.zzzw, r4.xxxy
  95: mad r2.z, r0.z, l(34.000000), l(1.000000)
  96: mul r0.z, r0.z, r2.z
  97: mul r2.z, r0.z, l(289.000000)
  98: ge r2.z, r2.z, -r2.z
  99: movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 100: mul r0.z, r0.z, r2.w
 101: frc r0.z, r0.z
 102: mad r0.z, r2.z, r0.z, r0.w
 103: mad r0.w, r0.z, l(34.000000), l(1.000000)
 104: mul r0.z, r0.z, r0.w
 105: mul r0.w, r0.z, l(289.000000)
 106: ge r0.w, r0.w, -r0.w
 107: movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 108: mul r0.z, r0.z, r2.w
 109: frc r0.z, r0.z
 110: mul r0.z, r0.z, r2.z
 111: mul r0.z, r0.z, l(0.024390)
 112: frc r0.z, r0.z
 113: mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
 114: round_ni r0.w, r0.w
 115: add r4.x, -r0.w, r0.z
 116: add r4.y, |r0.z|, l(-0.500000)
 117: dp2 r0.z, r4.xyxx, r4.xyxx
 118: rsq r0.z, r0.z
 119: mul r0.zw, r0.zzzz, r4.xxxy
 120: dp2 r0.x, r0.zwzz, r0.xyxx
 121: mad r0.y, r2.x, l(34.000000), l(1.000000)
 122: mul r0.y, r2.x, r0.y
 123: mul r0.z, r0.y, l(289.000000)
 124: ge r0.z, r0.z, -r0.z
 125: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 126: mul r0.y, r0.w, r0.y
 127: frc r0.y, r0.y
 128: mad r0.y, r0.z, r0.y, r2.y
 129: mad r0.z, r0.y, l(34.000000), l(1.000000)
 130: mul r0.y, r0.y, r0.z
 131: mul r0.z, r0.y, l(289.000000)
 132: ge r0.z, r0.z, -r0.z
 133: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 134: mul r0.y, r0.w, r0.y
 135: frc r0.y, r0.y
 136: mul r0.y, r0.y, r0.z
 137: mul r0.y, r0.y, l(0.024390)
 138: frc r0.y, r0.y
 139: mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
 140: round_ni r0.z, r0.z
 141: add r2.x, -r0.z, r0.y
 142: add r2.y, |r0.y|, l(-0.500000)
 143: dp2 r0.y, r2.xyxx, r2.xyxx
 144: rsq r0.y, r0.y
 145: mul r0.yz, r0.yyyy, r2.xxyx
 146: dp2 r0.y, r0.yzyy, r3.xyxx
 147: add r0.y, -r0.x, r0.y
 148: mad r0.x, r3.w, r0.y, r0.x
 149: add r0.y, -r0.x, r1.w
 150: mad r0.x, r3.z, r0.y, r0.x
 151: add r0.x, r0.x, l(0.500000)
 152: mad r2.xyzw, cb0[94].zzzz, cb2[0].xxxx, r1.xzxz
 153: round_ni r0.yz, r2.zzwz
 154: add r3.xy, r0.yzyy, l(1.000000, 1.000000, 0.000000, 0.000000)
 155: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 156: sincos r0.w, null, r0.w
 157: mul r0.w, r0.w, l(43758.546875)
 158: frc r0.w, r0.w
 159: frc r3.xy, r2.zwzz
 160: mul r2.xyzw, r2.xyzw, l(0.500000, 0.500000, 0.250000, 0.250000)
 161: mul r3.zw, r3.xxxy, r3.xxxy
 162: mad r3.xy, -r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
 163: mul r4.xy, r3.xyxx, r3.zwzz
 164: mad r3.xy, -r3.zwzz, r3.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 165: mul r0.w, r0.w, r4.x
 166: add r5.xyzw, r0.yzyz, l(1.000000, 0.000000, 0.000000, 1.000000)
 167: dp2 r0.y, r0.yzyy, l(12.989800, 78.233002, 0.000000, 0.000000)
 168: sincos r0.y, null, r0.y
 169: mul r0.y, r0.y, l(43758.546875)
 170: frc r0.y, r0.y
 171: dp2 r0.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 172: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 173: sincos r1.w, null, r1.w
 174: mul r1.w, r1.w, l(43758.546875)
 175: frc r1.w, r1.w
 176: mul r1.w, r1.w, r4.x
 177: mad r0.y, r3.x, r0.y, r1.w
 178: sincos r0.z, null, r0.z
 179: mul r0.z, r0.z, l(43758.546875)
 180: frc r0.z, r0.z
 181: mad r0.z, r3.x, r0.z, r0.w
 182: mul r0.z, r0.z, r4.y
 183: mad r0.y, r3.y, r0.y, r0.z
 184: round_ni r3.xyzw, r2.xyzw
 185: frc r2.xyzw, r2.xyzw
 186: add r4.xyzw, r3.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 187: dp2 r0.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 188: dp2 r0.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 189: sincos r0.zw, null, r0.zzzw
 190: mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 191: frc r0.zw, r0.zzzw
 192: add r4.xyzw, r3.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 193: dp2 r1.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 194: dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 195: sincos r4.x, null, r4.x
 196: mul r4.x, r4.x, l(43758.546875)
 197: frc r4.x, r4.x
 198: sincos r1.w, null, r1.w
 199: mul r1.w, r1.w, l(43758.546875)
 200: frc r1.w, r1.w
 201: mul r5.xyzw, r2.xyzw, r2.xyzw
 202: mad r2.xyzw, -r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 203: mul r6.xyzw, r2.xyzw, r5.xyzw
 204: mad r2.xyzw, -r5.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 205: mul r1.w, r1.w, r6.x
 206: mad r0.z, r2.x, r0.z, r1.w
 207: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 208: sincos r1.w, null, r1.w
 209: mul r1.w, r1.w, l(43758.546875)
 210: frc r1.w, r1.w
 211: mul r0.zw, r0.zzzw, r6.yyyx
 212: mad r0.w, r2.x, r1.w, r0.w
 213: mad r0.z, r2.y, r0.w, r0.z
 214: mul r0.z, r0.z, l(0.250000)
 215: mad r0.y, r0.y, l(0.125000), r0.z
 216: add r5.xyzw, r3.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 217: dp2 r0.z, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 218: sincos r0.z, null, r0.z
 219: mul r0.z, r0.z, l(43758.546875)
 220: dp2 r0.w, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 221: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 222: sincos r1.w, null, r1.w
 223: mul r1.w, r1.w, l(43758.546875)
 224: frc r1.w, r1.w
 225: sincos r0.w, null, r0.w
 226: mul r0.w, r0.w, l(43758.546875)
 227: frc r0.zw, r0.zzzw
 228: mul r0.w, r0.w, r6.z
 229: mad r0.w, r2.z, r1.w, r0.w
 230: mul r0.w, r0.w, r6.w
 231: mul r1.w, r4.x, r6.z
 232: mad r0.z, r2.z, r0.z, r1.w
 233: mad r0.z, r2.w, r0.z, r0.w
 234: mad r0.y, r0.z, l(0.500000), r0.y
 235: add r0.x, r0.y, r0.x
 236: mad r0.yz, cb0[94].xxxx, cb0[94].xxxx, r1.xxzx
 237: mov o1.xyz, r1.xyzx
 238: mul r1.xyzw, r0.yzyz, l(0.500000, 0.500000, 0.250000, 0.250000)
 239: round_ni r2.xyzw, r1.xyzw
 240: frc r1.xyzw, r1.xyzw
 241: add r3.xyzw, r2.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 242: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 243: dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 244: sincos r3.x, null, r3.x
 245: mul r3.x, r3.x, l(43758.546875)
 246: frc r3.x, r3.x
 247: sincos r0.w, null, r0.w
 248: mul r0.yzw, r0.yyzw, l(0.000000, 0.125000, 0.125000, 43758.546875)
 249: frc r0.w, r0.w
 250: mul r4.xyzw, r1.xyzw, r1.xyzw
 251: mad r1.xyzw, -r1.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 252: mul r5.xyzw, r1.xyzw, r4.xyzw
 253: mad r1.xyzw, -r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 254: mul r3.x, r3.x, r5.z
 255: mad r0.w, r1.z, r0.w, r3.x
 256: mul r0.w, r0.w, r5.w
 257: dp2 r3.x, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 258: sincos r3.x, null, r3.x
 259: mul r3.x, r3.x, l(43758.546875)
 260: frc r3.x, r3.x
 261: add r4.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 262: dp2 r2.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 263: dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 264: sincos r2.zw, null, r2.zzzw
 265: mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 266: frc r2.zw, r2.zzzw
 267: mul r2.zw, r2.zzzw, r5.zzzx
 268: mad r1.z, r1.z, r3.x, r2.z
 269: mad r0.w, r1.w, r1.z, r0.w
 270: mul r0.w, r0.w, l(0.250000)
 271: dp2 r1.z, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 272: add r3.xyzw, r2.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 273: sincos r1.z, null, r1.z
 274: mul r1.z, r1.z, l(43758.546875)
 275: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 276: dp2 r2.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 277: sincos r2.x, null, r2.x
 278: mul r2.x, r2.x, l(43758.546875)
 279: frc r2.x, r2.x
 280: mad r2.x, r1.x, r2.x, r2.w
 281: mul r2.x, r2.x, r5.y
 282: sincos r1.w, null, r1.w
 283: mul r1.w, r1.w, l(43758.546875)
 284: frc r1.zw, r1.zzzw
 285: mul r1.w, r1.w, r5.x
 286: mad r1.x, r1.x, r1.z, r1.w
 287: mad r1.x, r1.y, r1.x, r2.x
 288: mad r0.w, r1.x, l(0.125000), r0.w
 289: round_ni r1.xy, r0.yzyy
 290: frc r0.yz, r0.yyzy
 291: add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
 292: dp2 r1.z, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 293: sincos r1.z, null, r1.z
 294: mul r1.z, r1.z, l(43758.546875)
 295: frc r1.z, r1.z
 296: mul r2.xy, r0.yzyy, r0.yzyy
 297: mad r0.yz, -r0.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
 298: mul r2.zw, r0.yyyz, r2.xxxy
 299: mad r0.yz, -r2.xxyx, r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
 300: add r3.xyzw, r1.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 301: dp2 r1.x, r1.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 302: sincos r1.x, null, r1.x
 303: mul r1.x, r1.x, l(43758.546875)
 304: dp2 r1.y, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 305: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 306: sincos r1.yw, null, r1.yyyw
 307: mul r1.yw, r1.yyyw, l(0.000000, 43758.546875, 0.000000, 43758.546875)
 308: frc r1.xyw, r1.xyxw
 309: mul r1.zw, r1.zzzw, r2.zzzz
 310: mad r1.x, r0.y, r1.x, r1.w
 311: mad r0.y, r0.y, r1.y, r1.z
 312: mul r0.y, r0.y, r2.w
 313: mad r0.y, r0.z, r1.x, r0.y
 314: mad r0.y, r0.y, l(0.500000), r0.w
 315: mad r0.x, r0.x, r0.y, l(-0.500000)
 316: dp3 r0.y, cb1[1].xyzx, cb1[1].xyzx
 317: sqrt r0.y, r0.y
 318: mul r0.x, r0.y, r0.x
 319: mad r0.xyz, cb1[5].xyzx, r0.xxxx, cb1[7].xyzx
 320: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
 321: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
 322: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
 323: add r0.xyzw, r0.xyzw, cb1[3].xyzw
 324: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 325: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 326: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 327: mad o0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 328: dp3 r0.x, v1.xyzx, cb1[4].xyzx
 329: dp3 r0.y, v1.xyzx, cb1[5].xyzx
 330: dp3 r0.z, v1.xyzx, cb1[6].xyzx
 331: dp3 r0.w, r0.xyzx, r0.xyzx
 332: rsq r0.w, r0.w
 333: mul r0.xyz, r0.wwww, r0.xyzx
 334: mov o2.xyz, r0.xyzx
 335: mul r1.xyz, v2.yyyy, cb1[1].xyzx
 336: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
 337: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
 338: dp3 r0.w, r1.xyzx, r1.xyzx
 339: rsq r0.w, r0.w
 340: mul r1.xyz, r0.wwww, r1.xyzx
 341: mov o3.xyz, r1.xyzx
 342: mul r2.xyz, r0.zxyz, r1.yzxy
 343: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
 344: mul o4.xyz, r0.xyzx, v2.wwww
 345: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
 346: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
 347: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
 348: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
 349: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 350: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 351: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 352: mad r0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 353: mul r0.y, r0.y, cb0[96].x
 354: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
 355: mov o6.zw, r0.zzzw
 356: add o6.xy, r1.zzzz, r1.xwxx
 357: mov o7.xyzw, v3.xyzw
 358: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 13 math, 2 temp registers, 1 textures
Set 2D Texture "_CameraDepthTexture" to slot 0

Constant Buffer "$Globals" (4880 bytes) on slot 0 {
  Vector4 _ZBufferParams at 1568
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 1 {
  Vector4 Color_7896B6F at 32
  Float Vector1_A0FD746E at 48
  Float Vector1_9CBBF7B8 at 52
  Float Vector1_19F93CF9 at 56
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 3   xyz         1     NONE   float       
// TEXCOORD                 4   xyz         2     NONE   float       
// TEXCOORD                 5   xyz         3     NONE   float       
// TEXCOORD                 6   xyz         4     NONE   float       
// TEXCOORD                 7   xyz         5     NONE   float       
// TEXCOORD                 8   xyzw        6     NONE   float   xy w
// TEXCOORD                 9   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[99], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v6.xyw
      dcl_output o0.xyzw
      dcl_temps 2
   0: mad r0.x, cb1[3].x, l(2.000000), cb1[3].y
   1: add r0.x, r0.x, -cb1[3].x
   2: div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
   3: mul_sat r0.x, r0.x, -cb1[3].x
   4: mad r0.y, r0.x, l(-2.000000), l(3.000000)
   5: mul r0.x, r0.x, r0.x
   6: mul r0.x, r0.x, r0.y
   7: div r0.yz, v6.xxyx, v6.wwww
   8: sample r1.xyzw, r0.yzyy, t0.xyzw, s0
   9: mad r0.y, cb0[98].z, r1.x, cb0[98].w
  10: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
  11: add r0.y, r0.y, -v6.w
  12: mul_sat r0.y, r0.y, cb1[3].z
  13: mul o0.w, r0.y, r0.x
  14: mov o0.xyz, cb1[2].xyzx
  15: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 347 math
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Transparent+0" "RenderType"="Transparent" "RenderPipeline"="LightweightPipeline" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 347 math, 7 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (4896 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 2256
  Vector4 _TimeParameters at 1504
  Vector3 _WorldSpaceCameraPos at 1520
  Vector4 _ProjectionParams at 1536
  Vector4 _ShadowBias at 4864
  Vector3 _LightDirection at 4880
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 2 {
  Float Vector1_9E77EB2D at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// TEXCOORD                 3   xyz         2     NONE   float   xyz 
// TEXCOORD                 4   xyz         3     NONE   float   xyz 
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyz         6     NONE   float   xyz 
// TEXCOORD                 8   xyzw        7     NONE   float   xyzw
// TEXCOORD                 9   xyzw        8     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[306], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyz
      dcl_output o7.xyzw
      dcl_output o8.xyzw
      dcl_temps 7
   0: mul r0.x, cb0[94].z, cb2[0].x
   1: mul r0.yzw, v0.yyyy, cb1[1].xxyz
   2: mad r0.yzw, cb1[0].xxyz, v0.xxxx, r0.yyzw
   3: mad r0.yzw, cb1[2].xxyz, v0.zzzz, r0.yyzw
   4: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.yzwy
   5: add r0.yzw, r0.yyzw, cb1[3].xxyz
   6: add o6.xyz, -r0.yzwy, cb0[95].xyzx
   7: mad r0.xy, r0.xxxx, l(0.500000, 0.500000, 0.000000, 0.000000), r1.xzxx
   8: mul r0.xy, r0.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
   9: round_ni r0.zw, r0.xxxy
  10: frc r0.xy, r0.xyxx
  11: add r2.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
  12: mul r3.xyzw, r2.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
  13: ge r3.xyzw, r3.xyzw, -r3.zwzw
  14: movc r3.xyzw, r3.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  15: mul r2.xy, r2.xyxx, r3.zwzz
  16: frc r2.xy, r2.xyxx
  17: mul r2.xy, r2.xyxx, r3.xyxx
  18: mad r1.w, r2.x, l(34.000000), l(1.000000)
  19: mul r1.w, r2.x, r1.w
  20: mul r2.x, r1.w, l(289.000000)
  21: ge r2.x, r2.x, -r2.x
  22: movc r2.xz, r2.xxxx, l(289.000000,0,0.003460,0), l(-289.000000,0,-0.003460,0)
  23: mul r1.w, r1.w, r2.z
  24: frc r1.w, r1.w
  25: mad r1.w, r2.x, r1.w, r2.y
  26: mad r2.x, r1.w, l(34.000000), l(1.000000)
  27: mul r1.w, r1.w, r2.x
  28: mul r2.x, r1.w, l(289.000000)
  29: ge r2.x, r2.x, -r2.x
  30: movc r2.xy, r2.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  31: mul r1.w, r1.w, r2.y
  32: frc r1.w, r1.w
  33: mul r1.w, r1.w, r2.x
  34: mul r1.w, r1.w, l(0.024390)
  35: frc r1.w, r1.w
  36: mad r2.xy, r1.wwww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
  37: round_ni r1.w, r2.y
  38: add r3.x, -r1.w, r2.x
  39: add r3.y, |r2.x|, l(-0.500000)
  40: dp2 r1.w, r3.xyxx, r3.xyxx
  41: rsq r1.w, r1.w
  42: mul r2.xy, r1.wwww, r3.xyxx
  43: add r2.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
  44: dp2 r1.w, r2.xyxx, r2.zwzz
  45: add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
  46: mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  47: ge r3.xyzw, r3.xyzw, -r3.xyzw
  48: movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  49: movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  50: mul r2.zw, r2.zzzw, r4.zzzw
  51: mul r2.xy, r2.xyxx, r3.zwzz
  52: frc r2.xyzw, r2.xyzw
  53: mul r2.xy, r2.xyxx, r3.xyxx
  54: mul r2.zw, r2.zzzw, r4.xxxy
  55: mad r3.x, r2.z, l(34.000000), l(1.000000)
  56: mul r2.z, r2.z, r3.x
  57: mul r3.x, r2.z, l(289.000000)
  58: ge r3.x, r3.x, -r3.x
  59: movc r3.xy, r3.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  60: mul r2.z, r2.z, r3.y
  61: frc r2.z, r2.z
  62: mad r2.z, r3.x, r2.z, r2.w
  63: mad r2.w, r2.z, l(34.000000), l(1.000000)
  64: mul r2.z, r2.z, r2.w
  65: mul r2.w, r2.z, l(289.000000)
  66: ge r2.w, r2.w, -r2.w
  67: movc r3.xy, r2.wwww, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  68: mul r2.z, r2.z, r3.y
  69: frc r2.z, r2.z
  70: mul r2.z, r2.z, r3.x
  71: mul r2.z, r2.z, l(0.024390)
  72: frc r2.z, r2.z
  73: mad r2.zw, r2.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
  74: round_ni r2.w, r2.w
  75: add r3.x, -r2.w, r2.z
  76: add r3.y, |r2.z|, l(-0.500000)
  77: dp2 r2.z, r3.xyxx, r3.xyxx
  78: rsq r2.z, r2.z
  79: mul r2.zw, r2.zzzz, r3.xxxy
  80: add r3.xyzw, r0.xyxy, l(0.000000, -1.000000, -1.000000, 0.000000)
  81: dp2 r2.z, r2.zwzz, r3.zwzz
  82: add r1.w, r1.w, -r2.z
  83: mul r3.zw, r0.xxxy, r0.xxxy
  84: mul r3.zw, r0.xxxy, r3.zzzw
  85: mad r4.xy, r0.xyxx, l(6.000000, 6.000000, 0.000000, 0.000000), l(-15.000000, -15.000000, 0.000000, 0.000000)
  86: mad r4.xy, r0.xyxx, r4.xyxx, l(10.000000, 10.000000, 0.000000, 0.000000)
  87: mul r3.zw, r3.zzzw, r4.xxxy
  88: mad r1.w, r3.w, r1.w, r2.z
  89: mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  90: ge r4.xyzw, r4.xyzw, -r4.zwzw
  91: movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  92: mul r0.zw, r0.zzzw, r4.zzzw
  93: frc r0.zw, r0.zzzw
  94: mul r0.zw, r0.zzzw, r4.xxxy
  95: mad r2.z, r0.z, l(34.000000), l(1.000000)
  96: mul r0.z, r0.z, r2.z
  97: mul r2.z, r0.z, l(289.000000)
  98: ge r2.z, r2.z, -r2.z
  99: movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 100: mul r0.z, r0.z, r2.w
 101: frc r0.z, r0.z
 102: mad r0.z, r2.z, r0.z, r0.w
 103: mad r0.w, r0.z, l(34.000000), l(1.000000)
 104: mul r0.z, r0.z, r0.w
 105: mul r0.w, r0.z, l(289.000000)
 106: ge r0.w, r0.w, -r0.w
 107: movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 108: mul r0.z, r0.z, r2.w
 109: frc r0.z, r0.z
 110: mul r0.z, r0.z, r2.z
 111: mul r0.z, r0.z, l(0.024390)
 112: frc r0.z, r0.z
 113: mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
 114: round_ni r0.w, r0.w
 115: add r4.x, -r0.w, r0.z
 116: add r4.y, |r0.z|, l(-0.500000)
 117: dp2 r0.z, r4.xyxx, r4.xyxx
 118: rsq r0.z, r0.z
 119: mul r0.zw, r0.zzzz, r4.xxxy
 120: dp2 r0.x, r0.zwzz, r0.xyxx
 121: mad r0.y, r2.x, l(34.000000), l(1.000000)
 122: mul r0.y, r2.x, r0.y
 123: mul r0.z, r0.y, l(289.000000)
 124: ge r0.z, r0.z, -r0.z
 125: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 126: mul r0.y, r0.w, r0.y
 127: frc r0.y, r0.y
 128: mad r0.y, r0.z, r0.y, r2.y
 129: mad r0.z, r0.y, l(34.000000), l(1.000000)
 130: mul r0.y, r0.y, r0.z
 131: mul r0.z, r0.y, l(289.000000)
 132: ge r0.z, r0.z, -r0.z
 133: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 134: mul r0.y, r0.w, r0.y
 135: frc r0.y, r0.y
 136: mul r0.y, r0.y, r0.z
 137: mul r0.y, r0.y, l(0.024390)
 138: frc r0.y, r0.y
 139: mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
 140: round_ni r0.z, r0.z
 141: add r2.x, -r0.z, r0.y
 142: add r2.y, |r0.y|, l(-0.500000)
 143: dp2 r0.y, r2.xyxx, r2.xyxx
 144: rsq r0.y, r0.y
 145: mul r0.yz, r0.yyyy, r2.xxyx
 146: dp2 r0.y, r0.yzyy, r3.xyxx
 147: add r0.y, -r0.x, r0.y
 148: mad r0.x, r3.w, r0.y, r0.x
 149: add r0.y, -r0.x, r1.w
 150: mad r0.x, r3.z, r0.y, r0.x
 151: add r0.x, r0.x, l(0.500000)
 152: mad r2.xyzw, cb0[94].zzzz, cb2[0].xxxx, r1.xzxz
 153: round_ni r0.yz, r2.zzwz
 154: add r3.xy, r0.yzyy, l(1.000000, 1.000000, 0.000000, 0.000000)
 155: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 156: sincos r0.w, null, r0.w
 157: mul r0.w, r0.w, l(43758.546875)
 158: frc r0.w, r0.w
 159: frc r3.xy, r2.zwzz
 160: mul r2.xyzw, r2.xyzw, l(0.500000, 0.500000, 0.250000, 0.250000)
 161: mul r3.zw, r3.xxxy, r3.xxxy
 162: mad r3.xy, -r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
 163: mul r4.xy, r3.xyxx, r3.zwzz
 164: mad r3.xy, -r3.zwzz, r3.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 165: mul r0.w, r0.w, r4.x
 166: add r5.xyzw, r0.yzyz, l(1.000000, 0.000000, 0.000000, 1.000000)
 167: dp2 r0.y, r0.yzyy, l(12.989800, 78.233002, 0.000000, 0.000000)
 168: sincos r0.y, null, r0.y
 169: mul r0.y, r0.y, l(43758.546875)
 170: frc r0.y, r0.y
 171: dp2 r0.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 172: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 173: sincos r1.w, null, r1.w
 174: mul r1.w, r1.w, l(43758.546875)
 175: frc r1.w, r1.w
 176: mul r1.w, r1.w, r4.x
 177: mad r0.y, r3.x, r0.y, r1.w
 178: sincos r0.z, null, r0.z
 179: mul r0.z, r0.z, l(43758.546875)
 180: frc r0.z, r0.z
 181: mad r0.z, r3.x, r0.z, r0.w
 182: mul r0.z, r0.z, r4.y
 183: mad r0.y, r3.y, r0.y, r0.z
 184: round_ni r3.xyzw, r2.xyzw
 185: frc r2.xyzw, r2.xyzw
 186: add r4.xyzw, r3.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 187: dp2 r0.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 188: dp2 r0.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 189: sincos r0.zw, null, r0.zzzw
 190: mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 191: frc r0.zw, r0.zzzw
 192: add r4.xyzw, r3.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 193: dp2 r1.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 194: dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 195: sincos r4.x, null, r4.x
 196: mul r4.x, r4.x, l(43758.546875)
 197: frc r4.x, r4.x
 198: sincos r1.w, null, r1.w
 199: mul r1.w, r1.w, l(43758.546875)
 200: frc r1.w, r1.w
 201: mul r5.xyzw, r2.xyzw, r2.xyzw
 202: mad r2.xyzw, -r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 203: mul r6.xyzw, r2.xyzw, r5.xyzw
 204: mad r2.xyzw, -r5.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 205: mul r1.w, r1.w, r6.x
 206: mad r0.z, r2.x, r0.z, r1.w
 207: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 208: sincos r1.w, null, r1.w
 209: mul r1.w, r1.w, l(43758.546875)
 210: frc r1.w, r1.w
 211: mul r0.zw, r0.zzzw, r6.yyyx
 212: mad r0.w, r2.x, r1.w, r0.w
 213: mad r0.z, r2.y, r0.w, r0.z
 214: mul r0.z, r0.z, l(0.250000)
 215: mad r0.y, r0.y, l(0.125000), r0.z
 216: add r5.xyzw, r3.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 217: dp2 r0.z, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 218: sincos r0.z, null, r0.z
 219: mul r0.z, r0.z, l(43758.546875)
 220: dp2 r0.w, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 221: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 222: sincos r1.w, null, r1.w
 223: mul r1.w, r1.w, l(43758.546875)
 224: frc r1.w, r1.w
 225: sincos r0.w, null, r0.w
 226: mul r0.w, r0.w, l(43758.546875)
 227: frc r0.zw, r0.zzzw
 228: mul r0.w, r0.w, r6.z
 229: mad r0.w, r2.z, r1.w, r0.w
 230: mul r0.w, r0.w, r6.w
 231: mul r1.w, r4.x, r6.z
 232: mad r0.z, r2.z, r0.z, r1.w
 233: mad r0.z, r2.w, r0.z, r0.w
 234: mad r0.y, r0.z, l(0.500000), r0.y
 235: add r0.x, r0.y, r0.x
 236: mad r0.yz, cb0[94].xxxx, cb0[94].xxxx, r1.xxzx
 237: mov o2.xyz, r1.xyzx
 238: mul r1.xyzw, r0.yzyz, l(0.500000, 0.500000, 0.250000, 0.250000)
 239: round_ni r2.xyzw, r1.xyzw
 240: frc r1.xyzw, r1.xyzw
 241: add r3.xyzw, r2.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 242: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 243: dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 244: sincos r3.x, null, r3.x
 245: mul r3.x, r3.x, l(43758.546875)
 246: frc r3.x, r3.x
 247: sincos r0.w, null, r0.w
 248: mul r0.yzw, r0.yyzw, l(0.000000, 0.125000, 0.125000, 43758.546875)
 249: frc r0.w, r0.w
 250: mul r4.xyzw, r1.xyzw, r1.xyzw
 251: mad r1.xyzw, -r1.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 252: mul r5.xyzw, r1.xyzw, r4.xyzw
 253: mad r1.xyzw, -r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 254: mul r3.x, r3.x, r5.z
 255: mad r0.w, r1.z, r0.w, r3.x
 256: mul r0.w, r0.w, r5.w
 257: dp2 r3.x, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 258: sincos r3.x, null, r3.x
 259: mul r3.x, r3.x, l(43758.546875)
 260: frc r3.x, r3.x
 261: add r4.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 262: dp2 r2.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 263: dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 264: sincos r2.zw, null, r2.zzzw
 265: mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 266: frc r2.zw, r2.zzzw
 267: mul r2.zw, r2.zzzw, r5.zzzx
 268: mad r1.z, r1.z, r3.x, r2.z
 269: mad r0.w, r1.w, r1.z, r0.w
 270: mul r0.w, r0.w, l(0.250000)
 271: dp2 r1.z, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 272: add r3.xyzw, r2.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 273: sincos r1.z, null, r1.z
 274: mul r1.z, r1.z, l(43758.546875)
 275: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 276: dp2 r2.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 277: sincos r2.x, null, r2.x
 278: mul r2.x, r2.x, l(43758.546875)
 279: frc r2.x, r2.x
 280: mad r2.x, r1.x, r2.x, r2.w
 281: mul r2.x, r2.x, r5.y
 282: sincos r1.w, null, r1.w
 283: mul r1.w, r1.w, l(43758.546875)
 284: frc r1.zw, r1.zzzw
 285: mul r1.w, r1.w, r5.x
 286: mad r1.x, r1.x, r1.z, r1.w
 287: mad r1.x, r1.y, r1.x, r2.x
 288: mad r0.w, r1.x, l(0.125000), r0.w
 289: round_ni r1.xy, r0.yzyy
 290: frc r0.yz, r0.yyzy
 291: add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
 292: dp2 r1.z, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 293: sincos r1.z, null, r1.z
 294: mul r1.z, r1.z, l(43758.546875)
 295: frc r1.z, r1.z
 296: mul r2.xy, r0.yzyy, r0.yzyy
 297: mad r0.yz, -r0.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
 298: mul r2.zw, r0.yyyz, r2.xxxy
 299: mad r0.yz, -r2.xxyx, r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
 300: add r3.xyzw, r1.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 301: dp2 r1.x, r1.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 302: sincos r1.x, null, r1.x
 303: mul r1.x, r1.x, l(43758.546875)
 304: dp2 r1.y, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 305: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 306: sincos r1.yw, null, r1.yyyw
 307: mul r1.yw, r1.yyyw, l(0.000000, 43758.546875, 0.000000, 43758.546875)
 308: frc r1.xyw, r1.xyxw
 309: mul r1.zw, r1.zzzw, r2.zzzz
 310: mad r1.x, r0.y, r1.x, r1.w
 311: mad r0.y, r0.y, r1.y, r1.z
 312: mul r0.y, r0.y, r2.w
 313: mad r0.y, r0.z, r1.x, r0.y
 314: mad r0.y, r0.y, l(0.500000), r0.w
 315: mad r0.x, r0.x, r0.y, l(-0.500000)
 316: dp3 r0.y, cb1[1].xyzx, cb1[1].xyzx
 317: sqrt r0.y, r0.y
 318: mul r0.x, r0.y, r0.x
 319: mad r0.xyz, cb1[5].xyzx, r0.xxxx, cb1[7].xyzx
 320: mul r1.xyz, r0.yyyy, cb1[1].xyzx
 321: mad r0.xyw, cb1[0].xyxz, r0.xxxx, r1.xyxz
 322: mad r0.xyz, cb1[2].xyzx, r0.zzzz, r0.xywx
 323: add r0.xyz, r0.xyzx, cb1[3].xyzx
 324: mad r0.xyz, cb0[305].xyzx, cb0[304].xxxx, r0.xyzx
 325: dp3 r1.x, v1.xyzx, cb1[4].xyzx
 326: dp3 r1.y, v1.xyzx, cb1[5].xyzx
 327: dp3 r1.z, v1.xyzx, cb1[6].xyzx
 328: dp3 r0.w, r1.xyzx, r1.xyzx
 329: rsq r0.w, r0.w
 330: mul r1.xyz, r0.wwww, r1.xyzx
 331: dp3_sat r0.w, cb0[305].xyzx, r1.xyzx
 332: add r0.w, -r0.w, l(1.000000)
 333: mul r0.w, r0.w, cb0[304].y
 334: mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
 335: mul r2.xyzw, r0.yyyy, cb0[142].xyzw
 336: mad r2.xyzw, cb0[141].xyzw, r0.xxxx, r2.xyzw
 337: mad r0.xyzw, cb0[143].xyzw, r0.zzzz, r2.xyzw
 338: add r0.xyzw, r0.xyzw, cb0[144].xyzw
 339: min o1.z, r0.w, r0.z
 340: mov o1.xyw, r0.xyxw
 341: mov o3.xyz, r1.xyzx
 342: mul r0.xyz, v2.yyyy, cb1[1].xyzx
 343: mad r0.xyz, cb1[0].xyzx, v2.xxxx, r0.xyzx
 344: mad r0.xyz, cb1[2].xyzx, v2.zzzz, r0.xyzx
 345: dp3 r0.w, r0.xyzx, r0.xyzx
 346: rsq r0.w, r0.w
 347: mul r0.xyz, r0.wwww, r0.xyzx
 348: mov o4.xyz, r0.xyzx
 349: mul r2.xyz, r0.yzxy, r1.zxyz
 350: mad r0.xyz, r1.yzxy, r0.zxyz, -r2.xyzx
 351: mul o5.xyz, r0.xyzx, v2.wwww
 352: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
 353: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
 354: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
 355: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
 356: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 357: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 358: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 359: mad r0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 360: mul r0.y, r0.y, cb0[96].x
 361: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
 362: mov o7.zw, r0.zzzw
 363: add o7.xy, r1.zzzz, r1.xwxx
 364: mov o8.xyzw, v3.xyzw
 365: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float       
// TEXCOORD                 3   xyz         2     NONE   float       
// TEXCOORD                 4   xyz         3     NONE   float       
// TEXCOORD                 5   xyz         4     NONE   float       
// TEXCOORD                 6   xyz         5     NONE   float       
// TEXCOORD                 7   xyz         6     NONE   float       
// TEXCOORD                 8   xyzw        7     NONE   float       
// TEXCOORD                 9   xyzw        8     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 341 math
 Pass {
  Name "DepthOnly"
  Tags { "LIGHTMODE"="DepthOnly" "QUEUE"="Transparent+0" "RenderType"="Transparent" "RenderPipeline"="LightweightPipeline" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 341 math, 7 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (4880 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 2256
  Vector4 _TimeParameters at 1504
  Vector3 _WorldSpaceCameraPos at 1520
  Vector4 _ProjectionParams at 1536
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerMaterial" (64 bytes) on slot 2 {
  Float Vector1_9E77EB2D at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// TEXCOORD                 3   xyz         2     NONE   float   xyz 
// TEXCOORD                 4   xyz         3     NONE   float   xyz 
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyz         6     NONE   float   xyz 
// TEXCOORD                 8   xyzw        7     NONE   float   xyzw
// TEXCOORD                 9   xyzw        8     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[145], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyz
      dcl_output o7.xyzw
      dcl_output o8.xyzw
      dcl_temps 7
   0: mov o0.xy, l(0,0,0,0)
   1: mul r0.x, cb0[94].z, cb2[0].x
   2: mul r0.yzw, v0.yyyy, cb1[1].xxyz
   3: mad r0.yzw, cb1[0].xxyz, v0.xxxx, r0.yyzw
   4: mad r0.yzw, cb1[2].xxyz, v0.zzzz, r0.yyzw
   5: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.yzwy
   6: add r0.yzw, r0.yyzw, cb1[3].xxyz
   7: add o6.xyz, -r0.yzwy, cb0[95].xyzx
   8: mad r0.xy, r0.xxxx, l(0.500000, 0.500000, 0.000000, 0.000000), r1.xzxx
   9: mul r0.xy, r0.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
  10: round_ni r0.zw, r0.xxxy
  11: frc r0.xy, r0.xyxx
  12: add r2.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
  13: mul r3.xyzw, r2.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
  14: ge r3.xyzw, r3.xyzw, -r3.zwzw
  15: movc r3.xyzw, r3.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  16: mul r2.xy, r2.xyxx, r3.zwzz
  17: frc r2.xy, r2.xyxx
  18: mul r2.xy, r2.xyxx, r3.xyxx
  19: mad r1.w, r2.x, l(34.000000), l(1.000000)
  20: mul r1.w, r2.x, r1.w
  21: mul r2.x, r1.w, l(289.000000)
  22: ge r2.x, r2.x, -r2.x
  23: movc r2.xz, r2.xxxx, l(289.000000,0,0.003460,0), l(-289.000000,0,-0.003460,0)
  24: mul r1.w, r1.w, r2.z
  25: frc r1.w, r1.w
  26: mad r1.w, r2.x, r1.w, r2.y
  27: mad r2.x, r1.w, l(34.000000), l(1.000000)
  28: mul r1.w, r1.w, r2.x
  29: mul r2.x, r1.w, l(289.000000)
  30: ge r2.x, r2.x, -r2.x
  31: movc r2.xy, r2.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  32: mul r1.w, r1.w, r2.y
  33: frc r1.w, r1.w
  34: mul r1.w, r1.w, r2.x
  35: mul r1.w, r1.w, l(0.024390)
  36: frc r1.w, r1.w
  37: mad r2.xy, r1.wwww, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
  38: round_ni r1.w, r2.y
  39: add r3.x, -r1.w, r2.x
  40: add r3.y, |r2.x|, l(-0.500000)
  41: dp2 r1.w, r3.xyxx, r3.xyxx
  42: rsq r1.w, r1.w
  43: mul r2.xy, r1.wwww, r3.xyxx
  44: add r2.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
  45: dp2 r1.w, r2.xyxx, r2.zwzz
  46: add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
  47: mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  48: ge r3.xyzw, r3.xyzw, -r3.xyzw
  49: movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  50: movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  51: mul r2.zw, r2.zzzw, r4.zzzw
  52: mul r2.xy, r2.xyxx, r3.zwzz
  53: frc r2.xyzw, r2.xyzw
  54: mul r2.xy, r2.xyxx, r3.xyxx
  55: mul r2.zw, r2.zzzw, r4.xxxy
  56: mad r3.x, r2.z, l(34.000000), l(1.000000)
  57: mul r2.z, r2.z, r3.x
  58: mul r3.x, r2.z, l(289.000000)
  59: ge r3.x, r3.x, -r3.x
  60: movc r3.xy, r3.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  61: mul r2.z, r2.z, r3.y
  62: frc r2.z, r2.z
  63: mad r2.z, r3.x, r2.z, r2.w
  64: mad r2.w, r2.z, l(34.000000), l(1.000000)
  65: mul r2.z, r2.z, r2.w
  66: mul r2.w, r2.z, l(289.000000)
  67: ge r2.w, r2.w, -r2.w
  68: movc r3.xy, r2.wwww, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
  69: mul r2.z, r2.z, r3.y
  70: frc r2.z, r2.z
  71: mul r2.z, r2.z, r3.x
  72: mul r2.z, r2.z, l(0.024390)
  73: frc r2.z, r2.z
  74: mad r2.zw, r2.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
  75: round_ni r2.w, r2.w
  76: add r3.x, -r2.w, r2.z
  77: add r3.y, |r2.z|, l(-0.500000)
  78: dp2 r2.z, r3.xyxx, r3.xyxx
  79: rsq r2.z, r2.z
  80: mul r2.zw, r2.zzzz, r3.xxxy
  81: add r3.xyzw, r0.xyxy, l(0.000000, -1.000000, -1.000000, 0.000000)
  82: dp2 r2.z, r2.zwzz, r3.zwzz
  83: add r1.w, r1.w, -r2.z
  84: mul r3.zw, r0.xxxy, r0.xxxy
  85: mul r3.zw, r0.xxxy, r3.zzzw
  86: mad r4.xy, r0.xyxx, l(6.000000, 6.000000, 0.000000, 0.000000), l(-15.000000, -15.000000, 0.000000, 0.000000)
  87: mad r4.xy, r0.xyxx, r4.xyxx, l(10.000000, 10.000000, 0.000000, 0.000000)
  88: mul r3.zw, r3.zzzw, r4.xxxy
  89: mad r1.w, r3.w, r1.w, r2.z
  90: mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
  91: ge r4.xyzw, r4.xyzw, -r4.zwzw
  92: movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
  93: mul r0.zw, r0.zzzw, r4.zzzw
  94: frc r0.zw, r0.zzzw
  95: mul r0.zw, r0.zzzw, r4.xxxy
  96: mad r2.z, r0.z, l(34.000000), l(1.000000)
  97: mul r0.z, r0.z, r2.z
  98: mul r2.z, r0.z, l(289.000000)
  99: ge r2.z, r2.z, -r2.z
 100: movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 101: mul r0.z, r0.z, r2.w
 102: frc r0.z, r0.z
 103: mad r0.z, r2.z, r0.z, r0.w
 104: mad r0.w, r0.z, l(34.000000), l(1.000000)
 105: mul r0.z, r0.z, r0.w
 106: mul r0.w, r0.z, l(289.000000)
 107: ge r0.w, r0.w, -r0.w
 108: movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 109: mul r0.z, r0.z, r2.w
 110: frc r0.z, r0.z
 111: mul r0.z, r0.z, r2.z
 112: mul r0.z, r0.z, l(0.024390)
 113: frc r0.z, r0.z
 114: mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
 115: round_ni r0.w, r0.w
 116: add r4.x, -r0.w, r0.z
 117: add r4.y, |r0.z|, l(-0.500000)
 118: dp2 r0.z, r4.xyxx, r4.xyxx
 119: rsq r0.z, r0.z
 120: mul r0.zw, r0.zzzz, r4.xxxy
 121: dp2 r0.x, r0.zwzz, r0.xyxx
 122: mad r0.y, r2.x, l(34.000000), l(1.000000)
 123: mul r0.y, r2.x, r0.y
 124: mul r0.z, r0.y, l(289.000000)
 125: ge r0.z, r0.z, -r0.z
 126: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 127: mul r0.y, r0.w, r0.y
 128: frc r0.y, r0.y
 129: mad r0.y, r0.z, r0.y, r2.y
 130: mad r0.z, r0.y, l(34.000000), l(1.000000)
 131: mul r0.y, r0.y, r0.z
 132: mul r0.z, r0.y, l(289.000000)
 133: ge r0.z, r0.z, -r0.z
 134: movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
 135: mul r0.y, r0.w, r0.y
 136: frc r0.y, r0.y
 137: mul r0.y, r0.y, r0.z
 138: mul r0.y, r0.y, l(0.024390)
 139: frc r0.y, r0.y
 140: mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
 141: round_ni r0.z, r0.z
 142: add r2.x, -r0.z, r0.y
 143: add r2.y, |r0.y|, l(-0.500000)
 144: dp2 r0.y, r2.xyxx, r2.xyxx
 145: rsq r0.y, r0.y
 146: mul r0.yz, r0.yyyy, r2.xxyx
 147: dp2 r0.y, r0.yzyy, r3.xyxx
 148: add r0.y, -r0.x, r0.y
 149: mad r0.x, r3.w, r0.y, r0.x
 150: add r0.y, -r0.x, r1.w
 151: mad r0.x, r3.z, r0.y, r0.x
 152: add r0.x, r0.x, l(0.500000)
 153: mad r2.xyzw, cb0[94].zzzz, cb2[0].xxxx, r1.xzxz
 154: round_ni r0.yz, r2.zzwz
 155: add r3.xy, r0.yzyy, l(1.000000, 1.000000, 0.000000, 0.000000)
 156: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 157: sincos r0.w, null, r0.w
 158: mul r0.w, r0.w, l(43758.546875)
 159: frc r0.w, r0.w
 160: frc r3.xy, r2.zwzz
 161: mul r2.xyzw, r2.xyzw, l(0.500000, 0.500000, 0.250000, 0.250000)
 162: mul r3.zw, r3.xxxy, r3.xxxy
 163: mad r3.xy, -r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
 164: mul r4.xy, r3.xyxx, r3.zwzz
 165: mad r3.xy, -r3.zwzz, r3.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 166: mul r0.w, r0.w, r4.x
 167: add r5.xyzw, r0.yzyz, l(1.000000, 0.000000, 0.000000, 1.000000)
 168: dp2 r0.y, r0.yzyy, l(12.989800, 78.233002, 0.000000, 0.000000)
 169: sincos r0.y, null, r0.y
 170: mul r0.y, r0.y, l(43758.546875)
 171: frc r0.y, r0.y
 172: dp2 r0.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 173: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 174: sincos r1.w, null, r1.w
 175: mul r1.w, r1.w, l(43758.546875)
 176: frc r1.w, r1.w
 177: mul r1.w, r1.w, r4.x
 178: mad r0.y, r3.x, r0.y, r1.w
 179: sincos r0.z, null, r0.z
 180: mul r0.z, r0.z, l(43758.546875)
 181: frc r0.z, r0.z
 182: mad r0.z, r3.x, r0.z, r0.w
 183: mul r0.z, r0.z, r4.y
 184: mad r0.y, r3.y, r0.y, r0.z
 185: round_ni r3.xyzw, r2.xyzw
 186: frc r2.xyzw, r2.xyzw
 187: add r4.xyzw, r3.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 188: dp2 r0.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 189: dp2 r0.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 190: sincos r0.zw, null, r0.zzzw
 191: mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 192: frc r0.zw, r0.zzzw
 193: add r4.xyzw, r3.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 194: dp2 r1.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 195: dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 196: sincos r4.x, null, r4.x
 197: mul r4.x, r4.x, l(43758.546875)
 198: frc r4.x, r4.x
 199: sincos r1.w, null, r1.w
 200: mul r1.w, r1.w, l(43758.546875)
 201: frc r1.w, r1.w
 202: mul r5.xyzw, r2.xyzw, r2.xyzw
 203: mad r2.xyzw, -r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 204: mul r6.xyzw, r2.xyzw, r5.xyzw
 205: mad r2.xyzw, -r5.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 206: mul r1.w, r1.w, r6.x
 207: mad r0.z, r2.x, r0.z, r1.w
 208: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 209: sincos r1.w, null, r1.w
 210: mul r1.w, r1.w, l(43758.546875)
 211: frc r1.w, r1.w
 212: mul r0.zw, r0.zzzw, r6.yyyx
 213: mad r0.w, r2.x, r1.w, r0.w
 214: mad r0.z, r2.y, r0.w, r0.z
 215: mul r0.z, r0.z, l(0.250000)
 216: mad r0.y, r0.y, l(0.125000), r0.z
 217: add r5.xyzw, r3.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 218: dp2 r0.z, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 219: sincos r0.z, null, r0.z
 220: mul r0.z, r0.z, l(43758.546875)
 221: dp2 r0.w, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 222: dp2 r1.w, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 223: sincos r1.w, null, r1.w
 224: mul r1.w, r1.w, l(43758.546875)
 225: frc r1.w, r1.w
 226: sincos r0.w, null, r0.w
 227: mul r0.w, r0.w, l(43758.546875)
 228: frc r0.zw, r0.zzzw
 229: mul r0.w, r0.w, r6.z
 230: mad r0.w, r2.z, r1.w, r0.w
 231: mul r0.w, r0.w, r6.w
 232: mul r1.w, r4.x, r6.z
 233: mad r0.z, r2.z, r0.z, r1.w
 234: mad r0.z, r2.w, r0.z, r0.w
 235: mad r0.y, r0.z, l(0.500000), r0.y
 236: add r0.x, r0.y, r0.x
 237: mad r0.yz, cb0[94].xxxx, cb0[94].xxxx, r1.xxzx
 238: mov o2.xyz, r1.xyzx
 239: mul r1.xyzw, r0.yzyz, l(0.500000, 0.500000, 0.250000, 0.250000)
 240: round_ni r2.xyzw, r1.xyzw
 241: frc r1.xyzw, r1.xyzw
 242: add r3.xyzw, r2.zwzw, l(0.000000, 1.000000, 1.000000, 1.000000)
 243: dp2 r0.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 244: dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 245: sincos r3.x, null, r3.x
 246: mul r3.x, r3.x, l(43758.546875)
 247: frc r3.x, r3.x
 248: sincos r0.w, null, r0.w
 249: mul r0.yzw, r0.yyzw, l(0.000000, 0.125000, 0.125000, 43758.546875)
 250: frc r0.w, r0.w
 251: mul r4.xyzw, r1.xyzw, r1.xyzw
 252: mad r1.xyzw, -r1.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
 253: mul r5.xyzw, r1.xyzw, r4.xyzw
 254: mad r1.xyzw, -r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 255: mul r3.x, r3.x, r5.z
 256: mad r0.w, r1.z, r0.w, r3.x
 257: mul r0.w, r0.w, r5.w
 258: dp2 r3.x, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 259: sincos r3.x, null, r3.x
 260: mul r3.x, r3.x, l(43758.546875)
 261: frc r3.x, r3.x
 262: add r4.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)
 263: dp2 r2.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 264: dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 265: sincos r2.zw, null, r2.zzzw
 266: mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
 267: frc r2.zw, r2.zzzw
 268: mul r2.zw, r2.zzzw, r5.zzzx
 269: mad r1.z, r1.z, r3.x, r2.z
 270: mad r0.w, r1.w, r1.z, r0.w
 271: mul r0.w, r0.w, l(0.250000)
 272: dp2 r1.z, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 273: add r3.xyzw, r2.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 274: sincos r1.z, null, r1.z
 275: mul r1.z, r1.z, l(43758.546875)
 276: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 277: dp2 r2.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 278: sincos r2.x, null, r2.x
 279: mul r2.x, r2.x, l(43758.546875)
 280: frc r2.x, r2.x
 281: mad r2.x, r1.x, r2.x, r2.w
 282: mul r2.x, r2.x, r5.y
 283: sincos r1.w, null, r1.w
 284: mul r1.w, r1.w, l(43758.546875)
 285: frc r1.zw, r1.zzzw
 286: mul r1.w, r1.w, r5.x
 287: mad r1.x, r1.x, r1.z, r1.w
 288: mad r1.x, r1.y, r1.x, r2.x
 289: mad r0.w, r1.x, l(0.125000), r0.w
 290: round_ni r1.xy, r0.yzyy
 291: frc r0.yz, r0.yyzy
 292: add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
 293: dp2 r1.z, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 294: sincos r1.z, null, r1.z
 295: mul r1.z, r1.z, l(43758.546875)
 296: frc r1.z, r1.z
 297: mul r2.xy, r0.yzyy, r0.yzyy
 298: mad r0.yz, -r0.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
 299: mul r2.zw, r0.yyyz, r2.xxxy
 300: mad r0.yz, -r2.xxyx, r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
 301: add r3.xyzw, r1.xyxy, l(1.000000, 0.000000, 0.000000, 1.000000)
 302: dp2 r1.x, r1.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 303: sincos r1.x, null, r1.x
 304: mul r1.x, r1.x, l(43758.546875)
 305: dp2 r1.y, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
 306: dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
 307: sincos r1.yw, null, r1.yyyw
 308: mul r1.yw, r1.yyyw, l(0.000000, 43758.546875, 0.000000, 43758.546875)
 309: frc r1.xyw, r1.xyxw
 310: mul r1.zw, r1.zzzw, r2.zzzz
 311: mad r1.x, r0.y, r1.x, r1.w
 312: mad r0.y, r0.y, r1.y, r1.z
 313: mul r0.y, r0.y, r2.w
 314: mad r0.y, r0.z, r1.x, r0.y
 315: mad r0.y, r0.y, l(0.500000), r0.w
 316: mad r0.x, r0.x, r0.y, l(-0.500000)
 317: dp3 r0.y, cb1[1].xyzx, cb1[1].xyzx
 318: sqrt r0.y, r0.y
 319: mul r0.x, r0.y, r0.x
 320: mad r0.xyz, cb1[5].xyzx, r0.xxxx, cb1[7].xyzx
 321: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
 322: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
 323: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
 324: add r0.xyzw, r0.xyzw, cb1[3].xyzw
 325: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 326: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 327: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 328: mad o1.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 329: dp3 r0.x, v1.xyzx, cb1[4].xyzx
 330: dp3 r0.y, v1.xyzx, cb1[5].xyzx
 331: dp3 r0.z, v1.xyzx, cb1[6].xyzx
 332: dp3 r0.w, r0.xyzx, r0.xyzx
 333: rsq r0.w, r0.w
 334: mul r0.xyz, r0.wwww, r0.xyzx
 335: mov o3.xyz, r0.xyzx
 336: mul r1.xyz, v2.yyyy, cb1[1].xyzx
 337: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
 338: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
 339: dp3 r0.w, r1.xyzx, r1.xyzx
 340: rsq r0.w, r0.w
 341: mul r1.xyz, r0.wwww, r1.xyzx
 342: mov o4.xyz, r1.xyzx
 343: mul r2.xyz, r0.zxyz, r1.yzxy
 344: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
 345: mul o5.xyz, r0.xyzx, v2.wwww
 346: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
 347: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
 348: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
 349: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
 350: mul r1.xyzw, r0.yyyy, cb0[142].xyzw
 351: mad r1.xyzw, cb0[141].xyzw, r0.xxxx, r1.xyzw
 352: mad r1.xyzw, cb0[143].xyzw, r0.zzzz, r1.xyzw
 353: mad r0.xyzw, cb0[144].xyzw, r0.wwww, r1.xyzw
 354: mul r0.y, r0.y, cb0[96].x
 355: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
 356: mov o7.zw, r0.zzzw
 357: add o7.xy, r1.zzzz, r1.xwxx
 358: mov o8.xyzw, v3.xyzw
 359: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float       
// TEXCOORD                 3   xyz         2     NONE   float       
// TEXCOORD                 4   xyz         3     NONE   float       
// TEXCOORD                 5   xyz         4     NONE   float       
// TEXCOORD                 6   xyz         5     NONE   float       
// TEXCOORD                 7   xyz         6     NONE   float       
// TEXCOORD                 8   xyzw        7     NONE   float       
// TEXCOORD                 9   xyzw        8     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
Fallback "Hidden/InternalErrorShader"
}